In [1]:
import re
import logging
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import math
import time
import pickle
from collections import defaultdict
from data.configs.demo import config
from collections import defaultdict

from transformers import AutoTokenizer, AutoModel, BertModel, BertConfig
from utils.Manager import Manager

from models.Embeddings.BERT import BERT_Embedding
from models.Encoders.CNN import CNN_Encoder,CNN_User_Encoder
from models.Encoders.RNN import RNN_Encoder,RNN_User_Encoder
from models.Encoders.MHA import MHA_Encoder, MHA_User_Encoder
from models.Modules.DRM import Matching_Reducer, Slicing_Reducer
from models.Rankers.BERT import BERT_Onepass_Ranker, BERT_Original_Ranker
from models.Rankers.CNN import CNN_Ranker
from models.Encoders.Pooling import Attention_Pooling, Average_Pooling

from models.Encoders.BERT import BERT_Encoder
from models.Encoders.Pooling import *

from models.ESM import ESM
from models.TTMS import TTMS
 
from models.Modules.Attention import MultiheadAttention, get_attn_mask, XSoftmax
torch.set_printoptions(threshold=100000)

In [4]:
import smtplib

server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
server.login('namespace.pt@gmail.com', 'zpt136099')

server.sendmail('namespace.pt@gmail.com','namespace.pt@gmail.com',
                'shitshitshit')

{}

In [ ]:
m = AutoModel.from_pretrained('bert-base-uncased',cache_dir=config.path + 'bert_cache/')

# t = AutoTokenizer.from_pretrained('bert-base-uncased', cache_dir=config.path + "bert_cache/")
# t2 = DebertaTokenizerFast.from_pretrained('microsoft/deberta-base', cache_dir=config.path + "bert_cache/")

In [2]:
# config.reducer = 'entity'
# config.embedding = 'deberta'
# config.bert = 'microsoft/deberta-base'
# config.device = 0

manager = Manager(config)
loaders = manager.prepare()
X1 = list(loaders[0])
X2 = list(loaders[1])
x1 = X1[0]
x2 = X2[0]

[2021-09-23 14:57:57,536] INFO (utils.Manager) Hyper Parameters are 
{
    "scale": "demo",
    "mode": "tune",
    "batch_size": 5,
    "k": 5,
    "threshold": -Infinity,
    "abs_length": 40,
    "signal_length": 100,
    "his_size": 50,
    "cdd_size": 5,
    "impr_size": 10,
    "dropout_p": 0.2,
    "lr": 0.0001,
    "bert_lr": 3e-05,
    "embedding": "bert",
    "encoderN": "cnn",
    "encoderU": "rnn",
    "selector": "sfi",
    "reducer": "matching",
    "ranker": "onepass",
    "embedding_dim": 768,
    "hidden_dim": 384,
    "base_rank": 0,
    "world_size": 0,
    "seed": 42,
    "granularity": "avg",
    "debias": false,
    "full_attn": true,
    "ascend_history": false,
    "save_pos": false,
    "sep_his": false,
    "diversify": false,
    "no_dedup": false,
    "no_order_embed": false,
    "no_rm_punc": false,
    "scheduler": "linear",
    "warmup": 100,
    "shuffle": false,
    "bert": "bert-base-uncased",
    "tb": false
}
[2021-09-23 14:57:57,536] INFO (utils.Man

In [7]:
X1[-1]['cdd_encoded_index']

tensor([[[12669,  4819,  2928,  2571,  4900,  1037,  9610,  2278,  2304,  7241,
           2005, 19451,  4465,  2578,  2016, 12739,  2014, 11018,  2007,  1037,
           7782,  6045,  1998,  1037, 11466, 19745,  9231,  1012,  9580, 13238,
           9777,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
         [ 5735,  4267,  5443,  1012, 18156,  2053,  1012,  1015,  3639,  1024,
           6928,  6385,  3539,  1011,  2051,  2674,  6279,  2054,  5735,  4267,
           2515,  2000,  1037,  3639,  

In [3]:
a = torch.zeros(5).long()
(a.bernoulli_() * torch.tensor([1,2,3,4,5])).unsqueeze(0)

tensor([[1, 0, 0, 4, 0]])

In [4]:
x1['user_index']

tensor([1, 2, 3, 4, 5])

In [16]:
embedding = BERT_Embedding(manager)

encoderN = CNN_Encoder(manager)
# encoderN = RNN_Encoder(manager)
# encoderN = MHA_Encoder(manager)

# encoderU = CNN_User_Encoder(manager)
encoderU = RNN_User_Encoder(manager)
# encoderU = MHA_User_Encoder(manager)
# encoderU = Attention_Pooling(manager)
# encoderU = Average_Pooling(manager)

reducer = Matching_Reducer(manager)
# reducer = Slicing_Reducer(manager)

# ranker = CNN_Ranker(manager)
# ranker = BERT_Onepass_Ranker(manager)
# ranker = BERT_Original_Ranker(manager)

model = TTMS(manager, embedding, encoderN, encoderU, reducer).to(manager.device)
# model = ESM(manager, embedding, encoderN, encoderU, reducer, ranker).to(manager.device)

In [17]:
# model.eval()
# a,b = model(x2)

a,b = model(x1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]) tensor([[ 0.0355,  0.0448,  0.0208, -0.0203,  0.0166,  0.0120,  0.0257, -0.0202,
         -0.0085, -0.0028, -0.0179,  0.0275,  0.0078,  0.0224,  0.0461, -0.0076,
          0.0014,  0.0550, -0.0108,  0.0278,  0.0370,  0.0274,  0.0493,  0.0446,
          0.0155, -0.0023,  0.0668,  0.0236,  0.0234,  0.0313,  0.0313,  0.0313,
          0.0313,  0.0313,  0.0313,  0.0313,  0.0313,  0.0313,  0.0313,  0.0313,
          0.0313,  0.0313,  0.0313,  0.0313,  0.0313,  0.0313,  0.0313,  0.0313,
          0.0313,  0.0313,  0.0313,  0.0313,  0.0313,  0.0