In [1]:
import re
import logging
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import math
import time
import pickle
from collections import defaultdict
from utils.utils import prepare, convert_tokens_to_words
from data.configs.demo import config
from collections import defaultdict

from transformers import AutoTokenizer, AutoModel
from utils.Manager import Manager

from models.Embeddings.BERT import BERT_Embedding
from models.Encoders.CNN import CNN_Encoder,CNN_User_Encoder
from models.Encoders.RNN import RNN_Encoder,RNN_User_Encoder
from models.Encoders.MHA import MHA_Encoder, MHA_User_Encoder
from models.Modules.DRM import Matching_Reducer, Slicing_Reducer
from models.Rankers.BERT import BERT_Onepass_Ranker, BERT_Original_Ranker
from models.Rankers.CNN import CNN_Ranker
from models.Encoders.Pooling import Attention_Pooling, Average_Pooling

from models.Encoders.BERT import BERT_Encoder
from models.Encoders.Pooling import *

from models.ESM import ESM
from models.TTMS import TTMS
 
from models.Modules.Attention import MultiheadAttention

loss = nn.NLLLoss()

m = AutoModel.from_pretrained('microsoft/deberta-base', cache_dir='../../../Data/bert_cache')
# t = AutoTokenizer.from_pretrained('microsoft/deberta-base', cache_dir='../../../Data/bert_cache')

In [7]:
attn_mask = torch.tensor([[1.,1,1,1,0],[1,0,0,0,0]])
hidden_states = torch.rand((2,3,4))
extended_attn_mask = m.encoder.get_attention_mask(attn_mask)
rel_pos = m.encoder.get_rel_pos(hidden_states)

In [6]:
rel_pos, extended_attn_mask

(tensor([[[ 0, -1, -2],
          [ 1,  0, -1],
          [ 2,  1,  0]]]),
 tensor([[[[1, 0, 1],
           [0, 0, 0],
           [1, 0, 1]]],
 
 
         [[[1, 0, 0],
           [0, 0, 0],
           [0, 0, 0]]]], dtype=torch.uint8))

In [3]:
# config.reducer = 'entity'
# config.embedding = 'deberta'
# config.bert = 'microsoft/deberta-base'
# config.device = 0

manager = Manager(config)
loaders = prepare(manager)
x1 = list(loaders[0])[0]
x2 = list(loaders[1])[0]

[2021-09-06 14:01:59,640] INFO (utils.utils) Hyper Parameters are 
scale:demo
batch_size:5
k:5
threshold:-inf
signal_length:100
his_size:50
impr_size:10
lr:0.0001
bert_lr:3e-05
hidden_dim:384
world_size:0
step:0
ascend_history:False
no_dedup:False
diversify:False
granularity:avg
no_sep_his:False
no_order_embed:False
bert:bert-base-uncased
[2021-09-06 14:01:59,641] INFO (utils.utils) preparing dataset...
[2021-09-06 14:01:59,646] INFO (utils.MIND) process NO.0 loading cached user behavior from data/cache/bert/MINDdemo_train/10/behaviors..pkl
[2021-09-06 14:01:59,660] INFO (utils.MIND) process NO.0 loading cached news tokenization from data/cache/bert/MINDdemo_train/news.pkl
[2021-09-06 14:02:00,511] INFO (utils.utils) deduplicating...
[2021-09-06 14:02:01,876] INFO (utils.MIND) process NO.0 loading cached user behavior from data/cache/bert/MINDdemo_dev/10/behaviors..pkl
[2021-09-06 14:02:01,878] INFO (utils.MIND) process NO.0 loading cached news tokenization from data/cache/bert/MINDdem

In [55]:
class TTMS(nn.Module):
    def __init__(self, config, embedding, encoderN, encoderU, reducer):
        super().__init__()

        self.scale = config.scale
        self.cdd_size = config.cdd_size
        self.batch_size = config.batch_size
        self.his_size = config.his_size
        self.signal_length = config.signal_length
        self.device = config.device

        self.embedding = embedding
        self.encoderN = encoderN
        self.encoderU = encoderU

        self.reducer = reducer
        self.bert = BERT_Encoder(config)

        self.granularity = config.granularity
        if self.granularity != 'token':
            self.register_buffer('cdd_dest', torch.zeros((self.batch_size, config.impr_size, config.signal_length * config.signal_length)), persistent=False)
            if config.reducer in ["bm25", "entity", "first"]:
                self.register_buffer('his_dest', torch.zeros((self.batch_size, self.his_size, (config.k + 1) * (config.k + 1))), persistent=False)
            else:
                self.register_buffer('his_dest', torch.zeros((self.batch_size, self.his_size, config.signal_length * config.signal_length)), persistent=False)

        self.userProject = nn.Sequential(
            nn.Linear(self.bert.hidden_dim, self.bert.hidden_dim),
            nn.LayerNorm(self.bert.hidden_dim),
            nn.Tanh()
        )

        self.register_buffer('extra_cls_mask', torch.ones(1,1), persistent=False)

        self.name = '__'.join(['ttms', self.encoderN.name, self.encoderU.name, config.reducer, self.granularity])
        config.name = self.name

    def clickPredictor(self, cdd_news_repr, user_repr):
        """ calculate batch of click probabolity

        Args:
            cdd_news_repr: news-level representation, [batch_size, cdd_size, hidden_dim]
            user_repr: user representation, [batch_size, 1, hidden_dim]

        Returns:
            score of each candidate news, [batch_size, cdd_size]
        """
        # print(user_repr.mean(), cdd_news_repr.mean(), user_repr.max(), cdd_news_repr.max(), user_repr.sum(), cdd_news_repr.sum())
        score = cdd_news_repr.matmul(user_repr.transpose(-2,-1)).squeeze(-1)
        return score

    def _forward(self,x):
        t1 = time.time()
        if self.granularity != 'token':
            batch_size = x['cdd_subword_index'].size(0)
            cdd_size = x['cdd_subword_index'].size(1)

            if self.training:
                if batch_size != self.batch_size:
                    cdd_dest = self.cdd_dest[:batch_size, :cdd_size]
                    his_dest = self.his_dest[:batch_size]
                else:
                    cdd_dest = self.cdd_dest[:, :cdd_size]
                    his_dest = self.his_dest

            # batch_size always equals 1 when evaluating
            else:
                cdd_dest = self.cdd_dest[[0], :cdd_size]
                his_dest = self.his_dest[[0]]

            cdd_subword_index = x['cdd_subword_index'].to(self.device)
            his_subword_index = x['his_subword_index'].to(self.device)
            his_signal_length = his_subword_index.size(-2)
            cdd_subword_index = cdd_subword_index[:, :, :, 0] * self.signal_length + cdd_subword_index[:, :, :, 1]
            his_subword_index = his_subword_index[:, :, :, 0] * his_signal_length + his_subword_index[:, :, :, 1]

            if self.training:
                cdd_subword_prefix = cdd_dest.scatter(dim=-1, index=cdd_subword_index, value=1) * x["cdd_mask"].to(self.device)
            else:
                cdd_subword_prefix = cdd_dest.scatter(dim=-1, index=cdd_subword_index, value=1)
            cdd_subword_prefix = cdd_subword_prefix.view(batch_size, cdd_size, self.signal_length, self.signal_length)

            his_subword_prefix = his_dest.scatter(dim=-1, index=his_subword_index, value=1) * x["his_mask"].to(self.device)
            his_subword_prefix = his_subword_prefix.view(batch_size, self.his_size, his_signal_length, his_signal_length)

            if self.granularity == 'avg':
                # average subword embeddings as the word embedding
                cdd_subword_prefix = F.normalize(cdd_subword_prefix, p=1, dim=-1)
                his_subword_prefix = F.normalize(his_subword_prefix, p=1, dim=-1)

            cdd_attn_mask = cdd_subword_prefix.matmul(x['cdd_attn_mask'].to(self.device).float().unsqueeze(-1))
            his_attn_mask = his_subword_prefix.matmul(x["his_attn_mask"].to(self.device).float().unsqueeze(-1)).squeeze(-1)
            his_refined_mask = None
            if 'his_refined_mask' in x:
                his_refined_mask = his_subword_prefix.matmul(x["his_refined_mask"].to(self.device).float().unsqueeze(-1)).squeeze(-1)

        else:
            cdd_subword_prefix = None
            his_subword_prefix = None
            cdd_attn_mask = x['cdd_attn_mask'].to(self.device)
            his_attn_mask = x["his_attn_mask"].to(self.device)
            his_refined_mask = None
            if 'his_refined_mask' in x:
                his_refined_mask = x["his_refined_mask"].to(self.device)

        t2 = time.time()

        cdd_news = x["cdd_encoded_index"].long().to(self.device)
        cdd_news_embedding = self.embedding(cdd_news, cdd_subword_prefix)

        his_news = x["his_encoded_index"].long().to(self.device)
        his_news_embedding = self.embedding(his_news, his_subword_prefix)

        t6 = time.time()
        _, cdd_news_repr = self.bert(
            cdd_news_embedding, cdd_attn_mask
        )
        his_news_encoded_embedding, his_news_repr = self.encoderN(
            his_news_embedding
        )

        t7 = time.time()
        # no need to calculate this if ps_terms are fixed in advance
        if self.reducer.name == 'matching':
            user_repr = self.encoderU(his_news_repr)
        else:
            user_repr = None
        
        t3 = time.time()

        ps_terms, ps_term_mask, kid = self.reducer(his_news_encoded_embedding, his_news_embedding, user_repr, his_news_repr, his_attn_mask, his_refined_mask)

        # append CLS to the entire browsing history, directly deriving user repr
        batch_size = ps_terms.size(0)
        ps_terms = torch.cat([his_news_embedding[:, 0, 0].unsqueeze(1), ps_terms], dim=-2)
        ps_term_mask = torch.cat([self.extra_cls_mask.expand(batch_size, 1), ps_term_mask], dim=-1)

        t4 = time.time()

        _, user_cls = self.bert(ps_terms.unsqueeze(1), ps_term_mask.unsqueeze(1))
        user_repr = self.userProject(user_cls)

        t5 = time.time()

        print("preparing time:{}, embedding time:{}, encoding time:{}, course profiling time:{}, selecting time:{}, profiling time:{}".format(t2-t1, t6-t2, t7-t6, t3-t7, t4-t3, t5-t4))

        return self.clickPredictor(cdd_news_repr, user_repr), kid, (user_repr, cdd_news_repr)

    def forward(self,x):
        """
        Decoupled function, score is unormalized click score
        """
        score, kid, extra = self._forward(x)

        if self.training:
            prob = nn.functional.log_softmax(score, dim=1)
        else:
            prob = torch.sigmoid(score)

        return prob, kid, extra, score

In [56]:
embedding = BERT_Embedding(manager)

encoderN = CNN_Encoder(manager)
# encoderN = RNN_Encoder(manager)
# encoderN = MHA_Encoder(manager)

# encoderU = CNN_User_Encoder(manager)
# encoderU = RNN_User_Encoder(manager)
# encoderU = MHA_User_Encoder(manager)
encoderU = Attention_Pooling(manager)
# encoderU = Average_Pooling(manager)

reducer = Matching_Reducer(manager)
# reducer = Slicing_Reducer(manager)

# ranker = CNN_Ranker(manager)
# ranker = BERT_Onepass_Ranker(manager)
# ranker = BERT_Original_Ranker(manager)

model = TTMS(manager, embedding, encoderN, encoderU, reducer).to(manager.device)

In [57]:
a,b,c,d = model(x1)
d.retain_grad()
a,d

preparing time:0.013997554779052734, embedding time:0.05136728286743164, encoding time:1.095184564590454, course profiling time:0.0003993511199951172, selecting time:0.055777549743652344, profiling time:2.38578462600708


(tensor([[-2.3739e+00, -3.9156e-01, -2.5645e+00, -2.5645e+00, -2.5645e+00],
         [-6.2833e+00, -3.4192e+00, -7.4988e+00, -2.2180e-01, -1.8093e+00],
         [-6.7023e+00, -1.2734e+01, -1.7231e-03, -8.7279e+00, -8.0205e+00],
         [-9.3084e+00, -7.9760e-01, -1.8439e+00, -9.6730e-01, -4.4922e+00],
         [-2.5075e+00, -3.0121e+00, -6.7501e+00, -6.1541e-01, -1.1155e+00]],
        grad_fn=<LogSoftmaxBackward>),
 tensor([[-3.3020, -1.3197, -3.4926, -3.4926, -3.4926],
         [-1.9839,  0.8802, -3.1994,  4.0776,  2.4901],
         [ 6.3503,  0.3183, 13.0509,  4.3247,  5.0321],
         [-7.8380,  0.6728, -0.3735,  0.5031, -3.0218],
         [-1.2666, -1.7712, -5.5092,  0.6255,  0.1254]],
        grad_fn=<SqueezeBackward1>))

In [58]:
ls = loss(a,target=x1['label'])
ls.backward()

In [ ]:
d.grad

tensor([[-0.2000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.2000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.2000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.2000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.2000,  0.0000,  0.0000,  0.0000,  0.0000]])