In [1]:
import torch
import numpy as np

In [4]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[4],[2]])

a == b

array([[False, False, False],
       [ True, False, False]])

In [6]:
news = torch.load('data/cache/tesrec__bert__cnn__lstm__matching__token__3/demo/dev/news.pt', map_location="cpu").numpy()
user = torch.load('data/cache/tesrec__bert__cnn__lstm__matching__token__3/demo/dev/user.pt', map_location="cpu").numpy()

In [3]:
a = torch.load("/data/v-pezhang/Code/Document-Reduction/Code/data/recall/news.pt")

In [4]:
a[2]

tensor(65540)

In [7]:
import faiss                   # make faiss  3available
index = faiss.IndexFlatIP(768)   # build the index
print(index.is_trained)

True


In [8]:
index.add(news)

In [9]:
D,I = index.search(user, 5)

In [12]:
I

array([[ 4108,  5783, 34847, 32717, 36269],
       [ 4108, 38524,  5783, 36269, 32717],
       [32717,  4108,  5783, 13073, 36269],
       [ 4108, 32717, 12803, 22515, 36269],
       [ 5783, 13073, 38524,  4108, 37604],
       [ 4108, 32717,  5783, 36269, 34847],
       [ 4108,  5783, 32717, 38524, 36269],
       [ 4108,  5783, 38524, 36269, 40067],
       [ 4108, 32717,  5783, 36269, 11848],
       [34842,  5783, 13073,  9567, 34847],
       [32717,  4108,  5783, 34847, 36269],
       [34842, 36055, 22515, 12439, 40054],
       [18367, 31096, 41732,  5783, 21490],
       [ 9567, 32717,  1613, 34842,  5783],
       [ 4108, 32717,  5783, 36269, 12803],
       [ 5783, 17709, 34842,  9567, 19521],
       [21553,  4108,  5783, 36390, 32717],
       [21553, 38524, 32717, 36390, 36269],
       [32717, 22515,  4108,  5783,  9567],
       [42137,  9567,  1613, 34842, 32717],
       [ 5783, 40109, 13073, 33986, 22515],
       [17000, 12699, 26070, 22582, 24233],
       [32717,  4108, 22515,  57

In [6]:
import torch

In [9]:
a = torch.tensor([1,2,3.,4], requires_grad=True)
a.retain_grad()

b = a.masked_fill(torch.tensor([0,0,0,1],dtype=torch.bool), torch.tensor(0))
b

tensor([1., 2., 3., 0.], grad_fn=<MaskedFillBackward1>)

In [10]:
loss = (b**2).sum()
loss.backward()

In [11]:
a.grad

tensor([2., 4., 6., 0.])